apiVersion: v1
kind: Service
metadata:
  name: image-converter-service
spec:
  type: LoadBalancer  # Change to NodePort if not using a cloud provider
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: image-converter
