name: Argo CD GitOps Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p ~/.kube  # Create the .kube directory if it doesn't exist
        echo "$KUBECONFIG_DATA" | base64 --decode > ~/.kube/config  # Decode and write the kubeconfig

    - name: Sync Argo CD Application
      run: |
        kubectl apply -f argocd-app.yaml -n argocd
